/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yelson
 */
public class TrackView extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form TrackView
     */
    int x = getWidth()/2; //La mitad del lienzo
    int y = getWidth()/2;
    Thread hilo;
    
    public TrackView() {
        initComponents();
        hilo = new Thread(this);
    }

    public void paint(Graphics g){
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight()); //Rellena el fondo
        g.setColor(Color.red);
        g.fillOval(x, y, 30, 30);
    }
    
    public void create(){
        hilo.start();
    }
    
    public void interrput(){
        hilo.suspend();
    }
    
    public void continueThread(){
        hilo.resume();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    //Toda la animación que quiera
    @Override
    public void run(){
        try{
            while(true){
                while(y<getHeight()-30){
                    Thread.sleep(50);
                    y+=10;
                    repaint(); // Lo repinta en el lugar nuevo
                }
                while(y>10){
                    Thread.sleep(50);
                    y-=10;
                    repaint(); // Lo repinta en el lugar nuevo
                }
            }
        }catch (InterruptedException ex) {
            Logger.getLogger(TrackView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
