/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ThreadRunner;

/**
 *
 * @author Yelson
 */
public class TrackView extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form TrackView
     */
    int x = getWidth()/2; //La mitad del lienzo
    int y = getWidth()/2;
    Thread hilo;
    ThreadRunner runner;
    ThreadRunner runner2;
    ThreadRunner runner3;
    
    public TrackView() {
        initComponents();
        hilo = new Thread(this);
        runner = new ThreadRunner(10,10);
        runner2 = new ThreadRunner(100,100);
        runner3 = new ThreadRunner(200,10);
    }

    public void paint(Graphics g){
        g.setColor(getBackground());
        g.setColor(Color.black);
        g.fillRect(0, 0, getWidth(), getHeight()); //Rellena el fondo
        
        //Aquí tengo que crear una funcion que haga todas las que se necesiten
        g.setColor(Color.blue);
        g.fillOval(runner.getX(), runner.getY(), 30, 30);
        g.setColor(Color.red);
        g.fillRect(runner2.getX(), runner2.getY(), 50, 25);
        g.setColor(Color.green);
        g.fillOval(runner3.getX(), runner3.getY(), 40, 25);
    }
    
    public void create(){
        hilo.start();
    }
    
    public void interrput(){
        hilo.suspend();
    }
    
    public void continueThread(){
        hilo.resume();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    //Toda la animación que quiera
    @Override
    public void run(){
        runner.start();
        runner2.start();
        runner3.start();
        while(true){
            try {
                Thread.sleep(5);
            } catch (InterruptedException ex) {
                Logger.getLogger(TrackView.class.getName()).log(Level.SEVERE, null, ex);
            }
            repaint();   
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
